# Generated by Django 4.1 on 2022-08-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Low'), ('2', 'Medium'), ('3', 'High'), ('4', 'Emergency')], default='0', max_length=1),
        ),
    ]
