# Generated by Django 4.1 on 2022-08-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='penalty',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reward',
        ),
        migrations.AddField(
            model_name='task',
            name='penalty',
            field=models.ManyToManyField(to='main_app.penalty'),
        ),
        migrations.AddField(
            model_name='task',
            name='reward',
            field=models.ManyToManyField(to='main_app.reward'),
        ),
    ]
